
name: science
channels:
  - conda-forge

dependencies:
  - astropy
  - autopep8
  - autovizwidget
  - basemap
  - beautifulsoup4
  - bitarray
  - black
  - bokeh
  - cartopy
  - cffi
  - conda-build
  - conda-lock
  - conda-wrappers
  - cython
  - dask
  - dask-core
  - datashader
  - ephem
  - flake8
  - flask
  - future
  - git
  - git-annex  # [not win]
  - h5py
  - hdf4
  - hdf5
  - holoviews
  - hvplot
  - ipykernel
  - ipython
  - ipywidgets
  - jedi
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-plotly-extension
  - jpype1
  - kiwisolver
  - matplotlib
  - mypy
  - nbconvert
  - nodejs
  - notebook
  - numba
  - numexpr
  - numpy
  - openjdk
  - openpyxl
  - pandas
  - param
  - pathlib
  - pep8
  - plotly
  - pyqt
  - pytables
  - pytest
  - python
  - pytz
  - pyzmq
  - requests
  - scikit-image
  - scikit-image
  - scikit-learn
  - scikit-rf
  - scipy
  - scipy
  - seaborn
  - skyfield
  - sphinx
  - sqlite
  - statsmodels
  - streamlit
  - streamz
  - swig
  - sympy
  - tqdm
  - traits
  - typing
  - typing_extensions
  - tzdata
  - wget  # [not win]
  - xarray
  - xlrd
  - yapf
  - yt
  - zeromq

 
