
name: gnuradio
channels:
  - conda-forge

dependencies:
  - python
  - jupyter
  - jupyterlab
  - gnuradio
  - gnuradio-satellites
  - gnuradio-osmosdr
  - gnuradio-soapy
  - soapysdr-module-plutosdr
  - construct
  - ipywidgets
  - nodejs
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - scipy
  - plotly
  - streamlit
  - orekit
  - conda-lock
  - basemap
  - cartopy
  - jupyterlab-plotly-extension
  - jupyterlab-git
  - git
  - git-annex
  - autopep8
  - autovizwidget
  - beautifulsoup4
  - bitarray
  - black
  - bokeh
  - cffi
  - jcc
  - conda-build
  - cython
  - dask
  - dask-core
  - datashader
  - ephem
  - flake8
  - flask
  - future
  - h5py
  - hdf4
  - hdf5
  - holoviews
  - hvplot
  - ipython
  - jedi
  - kiwisolver
  - mypy
  - nbconvert
  - numba
  - notebook
  - numexpr
  - param
  - pathlib
  - pep8
  - pyqt
  - pytables
  - pytest
  - pytz
  - pyzmq
  - requests
  - scikit-image
  - scikit-learn
  - scikit-rf
  - scipy
  - seaborn
  - sphinx
  - sqlite
  - statsmodels
  - streamz
  - swig
  - sympy
  - tqdm
  - traits
  - typing
  - typing_extensions
  - tzdata
  - wget
  - xarray
  - yapf
  - yt
  - zeromq
  - xlrd
  - openpyxl

 
